name: exercise_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.7
  flutter_svg: ^1.1.0
  chat_bubbles: ^1.6.0
  fluttertoast: ^8.0.0
  mailer: ^6.1.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.13
  video_player: ^2.8.2
  flutter_paypal_checkout: ^1.0.1
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/Images/train.jpg
    - assets/Images/dumbbell.png
    - assets/Images/OurLogo.png
    - assets/Images/profile_picture.jpg
    - assets/Images/post_image1.jpg
    
  fonts:
    - family: DancingScript
      fonts:
        - asset: fonts/CedarvilleCursive-Regular.ttf
