name: exercise_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.7
  flutter_svg: ^1.1.0
  chat_bubbles: ^1.6.0
  fluttertoast: ^8.0.0
  mailer: ^6.1.0
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/Images/train.jpg
    - assets/Images/dumbbell.png
    - assets/train.jpg


